language: php

env:
  - TESTING_FRAMEWORK=phpspec
  - TESTING_FRAMEWORK=behat

php: [5.3, 5.4, 5.5]

before_script:
  - curl http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source

script: if [ $TESTING_FRAMEWORK == "phpspec" ]; then vendor/bin/phpspec run -fpretty -v; elif [ $TESTING_FRAMEWORK == "behat" ]; then vendor/bin/behat -fpretty -v; fi
